[package]
build = "build.rs"
name = "rust-hyper-unixh2c"
version = "0.0.42"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
chrono = "0.4"
getset = "0.1"
humantime-serde = "1"
hyper = { version = "0.14", features = ["full", "deprecated", "backports"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
vergen = { version = "8", features = ["build", "cargo", "rustc", "si"] }
