[context_configuration]
dynamic_route_context = "/api/v1"

[server_configuration]
listeners = [
    { protocol = "HTTP2", socket_type = "UNIX", bind_address = "./socket" },
    { protocol = "HTTP1", socket_type = "TCP", bind_address = "[::]:8080" },
]
connection = { limit = 100, max_lifetime = "2min", graceful_shutdown_timeout = "5sec" }

[static_file_configuration]
root = "/Users/aaron/vscode/aaronr.digital"
precompressed = { br = false, gz = false }
client_error_page_path = "/notfound.html"
cache_rules = [
    { path_regex = '^/?notfound\.html', rule_type = "FIXED_TIME", duration = "5min" },
    { path_regex = '^/?vnstat/.*\.png$', rule_type = "MOD_TIME_PLUS_DELTA", duration = "15min" },
    { path_regex = '.*', rule_type = "FIXED_TIME", duration = "1hour" },
]

[command_configuration]
max_concurrent_commands = 1
semaphore_acquire_timeout = "200ms"
commands = [
    { id = "sleep", description = "sleep", command = "/bin/sleep", args = [
        "5",
    ] },
    { id = "vmstat", description = "vmstat", command = "/usr/bin/vmstat" },
    { id = "w", description = "w", command = "/usr/bin/w" },
]
